osx_image: xcode9.1
language: swift
xcode_sdk: iphonesimulator11.1
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/ThinCreditCard.xcworkspace -scheme ThinCreditCard-Example -destination 'platform=iOS Simulator,name=iPhone 7' -sdk iphonesimulator11.1 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
